function trl = getTrlStruct(N)

% trl é o struct com todas as propriedades do trial na ordem em que foram
% apresentados. É uma estrutura com propriedades redundantes, mastigadas,
% para serem agregadas na parte da análise. Para tanto, extrai informações
% do EDF e do mat
    trl = struct( ...
                'trlKeep',      cell(1,N), ...    % Se o trial foi mantido ou rejeitado
                'subjNum',      cell(1,N), ...
                'trlIdx',       cell(1,N), 'blkIdx',   cell(1,N), ...
                'trlDur',       cell(1,N), ...
                'trlLimTime',   cell(1,N), ...
                ...
                'tgtOri',       cell(1,N), 'nTgt',      cell(1,N), 'tgtIdx',  cell(1,N), ...
                'tgtPosDva',    cell(1,N), 'tgtPosPix', cell(1,N), ...
                'stmOri',       cell(1,N), 'nStm',      cell(1,N), ... stmIdx são todos
                'stmPosDva',    cell(1,N), 'stmPosPix', cell(1,N), ...
                ...
                'saccInt',      cell(1,N),... -(saccOn - P3Off), saccOn é 0; negativo: offset antes (do início) da sacada; positivo: offset depois (do início) da sacada
                ...                          % cauda bem negativa se sacada começa depois do fim do alvo
                'saccInt1',      cell(1,N),...
                'P3FixDurPerPhase', cell(1,N),...
                'p3EarlyStop',  cell(1,N),...
                'pinkNoiseDur', cell(1,N),...   % O período exato durante o qual o ruído rosa foi visto,
                ...                                % intervalo entre seu início e o fim da fixação na P3
                'saccAmpDva',   cell(1,N),...
                'saccVelDvas',  cell(1,N), ...
                'saccAccPix',   cell(1,N),...
                ...
                'probeSeen',   cell(1,N), ...    % Se o alvo da sacada já tinha sido forrageado
                'probeCat',     cell(1,N),...
                'probeOri',     cell(1,N), ...
                'probeForHistIdx', cell(1,N), ...
                'probePosPix',  cell(1,N), ...
                'probePosFixPix',  cell(1,N), ...
                'probeIdx', cell(1,N), ...
                ...
                'preProbeOri',       cell(1,N),...
                'preProbeFixDur',       cell(1,N),... 'preSaccISI', ...
                'preProbeCat',       cell(1,N),...
                'preProbePosPix',       cell(1,N), ...
                'preProbePosFixPix',       cell(1,N), ...
                'preProbeProbeDistDva', cell(1,N),...
                'preProbeIdx', cell(1,N), ...
                ...
                'nSaccProbeOri', cell(1,N),...
                ... % Não há duração para não sacádico
                'nSaccProbeCat', cell(1,N),...
                'nSaccProbePosPix',  cell(1,N), ...
                'preProbeNSaccProbeDistDva',  cell(1,N),...
                'nSaccProbeProbeDistDva',     cell(1,N),...
                'nSaccProbeProbeDistDeg',     cell(1,N),...
                'nSaccProbeIdx', cell(1,N), ...
                ...
                'forProbeOri',    cell(1,N),...
                'forProbeFixDur', cell(1,N),...
                'forProbeCat',    cell(1,N),...
                'forProbePosPix', cell(1,N),...
                'forProbeRecency',cell(1,N),...
                'forProbeIdx', cell(1,N), ...
                ...
                'forHistLen',     cell(1,N),...
                'forHistHasRep',  cell(1,N),...
                'forHistIdx',     cell(1,N),...
                'forHistIdxNoRep',  cell(1,N),...
                'forHistFixDur',  cell(1,N),...
                'forHistCat',  cell(1,N),...
                'forHistOri',  cell(1,N),...
                ...
                'probeResp',      cell(1,N),... 1 = distrator, 2 = alvo
                'nSaccProbeResp', cell(1,N),...
                'forProbeResp',   cell(1,N),...
                'allResp',        cell(1,N),...
                ...
                'probeHit',      cell(1,N),... 0 = inceorreto, 1 = correto
                'nSaccProbeHit', cell(1,N),...
                'forProbeHit',   cell(1,N),...
                'allHit',   cell(1,N),...
                ...
                'allProbesOrder',cell(1,N),...
                ...
                'phaseLimsIdx', cell(1,N),...
                'stmLimsIdx',   cell(1,N),...
                'fixLimsIdx',   cell(1,N),...
                'phaseLimsTime', cell(1,N),...
                'stmLimsTime',   cell(1,N),...
                'fixLimsTime',   cell(1,N),...
                'trlLimEvt',     cell(1,N), 'trlLimClk',cell(1,N));
%                 ...
%                 ...
%                 ...
%                 , ...
%                 'modTime',  cell(1,N), ...
%                 ...
%                 'p1Pos',    cell(1,N), 'p1PosPix', cell(1,N), ...
%                 'p1Dur',    cell(1,N), ...
%                 'p1LimEvt', cell(1,N), 'p1LimClk', cell(1,N), 'p1LimTime',cell(1,N), ...
%                 'p1FixPos', cell(1,N), ...
%                 'p1FixPosPix', cell(1,N), ...
%                 'p1FixSpread', cell(1,N),...
%                 'p1FixDur',    cell(1,N), ...
%                 'p1FixLimIdx', cell(1,N),...
%                 'p1FixLimAbs', cell(1,N),...
%                 'p1FixTimeIdx',cell(1,N),...
%                 'p1FixDetail', cell(1,N),...
%                 ...
%                 'p2Pos',      cell(1,N), ...
%                 'p2PosPix',   cell(1,N), ...
%                 'p2PosDist',  cell(1,N), ...
%                 'p2Dur',      cell(1,N), ...
%                 'p2LimIdx',   cell(1,N), ...
%                 'p2LimAbs',   cell(1,N), ...
%                 'p2FixIdx',   cell(1,N), ...
%                 'p2FixOnTgt', cell(1,N), ...
%                 'p2OnlyFixIdx',   cell(1,N), ...
%                 'p2NFix',         cell(1,N), ...
%                 'p2OnlyNFix',     cell(1,N), ...
%                 'p2NFixNoRep',    cell(1,N), ...
%                 'p2OnlyNFixNoRep',cell(1,N), ...
%                 'p2FixPos',       cell(1,N), ...
%                 'p2FixSpread',    cell(1,N),...
%                 'p2FixDist',cell(1,N), ... % Distância percorrida para alcançar aquela fixação
%                 'p2FixDur', cell(1,N), ...
%                 'p2FixLimIdx',  cell(1,N),...
%                 'p2FixLimAbs',  cell(1,N),...
%                 'p2FixTimeIdx', cell(1,N),...
%                 'p2FixDetail',  cell(1,N),...
%                 ...
%                 'p3Pos',    cell(1,N), ...
%                 'p3PosDist',cell(1,N), ...
%                 'p3ToP4PosDist',cell(1,N), ...      % Distância entre o estímulo fixado entre P2 e P3 e os estímulos perguntados em P4
%                 'p3ToP4PosDistm1',cell(1,N), ...
%                 'p3ToP4PosDist0',cell(1,N), ...
%                 'p3ToP4PosDist1',cell(1,N), ...
%                 'p3Dur',    cell(1,N), ...
%                 'p3LimIdx', cell(1,N), ...
%                 'p3LimAbs', cell(1,N), ...
%                 'p3FixIdx', cell(1,N), ...
%                 'p3OnlyFixOnTgt', cell(1,N), ...
%                 'p3OnlyFixIdx',   cell(1,N), ...
%                 'p3NFix',   cell(1,N), ...
%                 'p3OnlyNFix',   cell(1,N), ...
%                 'p3p2FixIdx', cell(1,N),...
%                 'p3FixPos', cell(1,N), ...
%                 'p3FixSpread', cell(1,N),...
%                 'p3FixDist',cell(1,N), ...
%                 'p3FixDur', cell(1,N), ...
%                 'p3FixLimIdx', cell(1,N),...
%                 'p3FixLimAbs', cell(1,N),...
%                 'p3FixTimeIdx', cell(1,N),...
%                 'p3FixDetail', cell(1,N),...
%                 'p3FixOffsetDelay', cell(1,N),...   % Quanto tempo demorou para terminar fixação em relação 
%                 ...                                 % ao fim do ruído rosa (**idealmente negativo**)
%                 'pMPos',    cell(1,N), ...
%                 'pMPosDist', cell(1,N), ...
%                 'pMDur',    cell(1,N), ...
%                 'pMLimIdx', cell(1,N), ...
%                 'pMLimAbs', cell(1,N), ...
%                 'pMFixIdx', cell(1,N), ...
%                 'pMOnlyFixOnTgt', cell(1,N), ...
%                 'pMOnlyFixIdx',   cell(1,N), ...
%                 'pMNFix',   cell(1,N), ...
%                 'pMOnlyNFix',   cell(1,N), ...
%                 'pMp3FixIdx', cell(1,N),...
%                 'pMFirstFixPos', cell(1,N), ...
%                 'pMFixPosPix', cell(1,N), ...
%                 'pMFixSpread', cell(1,N),...
%                 'pMFixDist',cell(1,N), ...
%                 'pMFixDur', cell(1,N), ...
%                 'pMFixLimIdx', cell(1,N),...
%                 'pMFixLimAbs', cell(1,N), ...
%                 'pMFixLimRel', cell(1,N), ...
%                 'pMFixTimeIdx', cell(1,N),...
%                 'pMFixDetail', cell(1,N),...
%                 'p4PosDist', cell(1,N),...      % A distância entre a fixação pós-ruído rosa
%                 ...                                 % e os estímulos estímulos perguntados
%                 'p4PosDistm1', cell(1,N),...
%                 'p4PosDist0', cell(1,N),...
%                 'p4PosDist1', cell(1,N),...
%                 'p4Dur',    cell(1,N), ...
%                 'p4LimIdx', cell(1,N), ...
%                 'p4LimAbs', cell(1,N), ...
%                 'p4IdxAsk', cell(1,N), ...
%                 'p4IdxStatus', cell(1,N), ...
%                 'p4StatusHas0and1', num2cell(zeros(1,N)),...
%                 'p4StatusHas0or1', num2cell(zeros(1,N)),...
%                 'p4AnsDur', cell(1,N), ...
%                 'p4AnsExp', cell(1,N), ...
%                 'p4AnsExpm1', cell(1,N), ...
%                 'p4AnsExp0', cell(1,N), ...
%                 'p4AnsExp1', cell(1,N), ...
%                 'p4AnsObsm1',cell(1,N), ...
%                 'p4AnsObs',cell(1,N), ...
%                 'p4AnsObs0',cell(1,N), ...
%                 'p4AnsObs1',cell(1,N), ...
%                 'p4IdxFB',cell(1,N), ...
%                 'p4AnsFBm1',cell(1,N), ...
%                 'p4AnsFB0',cell(1,N), ...
%                 'p4AnsFB1',cell(1,N));
end